apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infercrane-provider-deployment
  namespace: infercrane-system
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infercrane-provider-deployment
  namespace: infercrane-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infercrane-provider-deployment
subjects:
  - kind: ServiceAccount
    name: infercrane-control-plane
    namespace: infercrane-system
