// Command repo-context generates a deterministic, factual repository inventory.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	envPattern      = regexp.MustCompile(`INFERCRANE_[A-Z0-9_]+`)
	endpointPattern = regexp.MustCompile(`"(GET|POST|PUT|PATCH|DELETE) (/[^" ]*)"`)
	commandPattern  = regexp.MustCompile(`case "([a-z][a-z0-9-]*)"`)
	tablePattern    = regexp.MustCompile(`(?im)CREATE TABLE(?: IF NOT EXISTS)?\s+([a-z][a-z0-9_]*)`)
	linkPattern     = regexp.MustCompile(`\[[^]]+\]\(([^)]+)\)`)
)

type packageInfo struct {
	Path      string
	GoFiles   int
	TestFiles int
	Tests     []string
}

func main() {
	check := flag.Bool("check", false, "fail when the generated map is stale")
	flag.Parse()
	root, err := repositoryRoot()
	if err != nil {
		fatal(err)
	}
	content, err := generate(root)
	if err != nil {
		fatal(err)
	}
	if err := validateLinks(root); err != nil {
		fatal(err)
	}
	output := filepath.Join(root, "docs", "generated", "repository-map.md")
	if *check {
		existing, err := os.ReadFile(output)
		if err != nil || !bytes.Equal(existing, content) {
			fatal(fmt.Errorf("%s is stale; run make context", relative(root, output)))
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(output, content, 0o644); err != nil {
		fatal(err)
	}
}

func generate(root string) ([]byte, error) {
	packages := map[string]*packageInfo{}
	envs, endpoints, commands, tables := map[string]struct{}{}, map[string]struct{}{}, map[string]struct{}{}, map[string]struct{}{}
	var migrations, adrs []string
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel := relative(root, path)
		if entry.IsDir() {
			if skipRepositoryDirectory(rel) {
				return filepath.SkipDir
			}
			return nil
		}
		// Acceptance evidence uses named pipes to split human progress from
		// machine-readable output. Never open sockets, devices, FIFOs, or symlinks
		// while generating a source inventory: reads may block indefinitely and
		// ignored runtime artifacts are not repository context.
		if entry.Type()&os.ModeType != 0 {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if strings.HasSuffix(path, ".go") {
			dir := filepath.ToSlash(filepath.Dir(rel))
			info := packages[dir]
			if info == nil {
				info = &packageInfo{Path: dir}
				packages[dir] = info
			}
			if strings.HasSuffix(path, "_test.go") {
				info.TestFiles++
			} else {
				info.GoFiles++
			}
			file, err := parser.ParseFile(token.NewFileSet(), path, data, 0)
			if err != nil {
				return err
			}
			for _, declaration := range file.Decls {
				if fn, ok := declaration.(*ast.FuncDecl); ok && strings.HasPrefix(fn.Name.Name, "Test") {
					info.Tests = append(info.Tests, fn.Name.Name)
				}
			}
			collectMatches(envPattern, data, envs, 0)
			for _, match := range endpointPattern.FindAllSubmatch(data, -1) {
				endpoints[string(match[1])+" "+string(match[2])] = struct{}{}
			}
			if strings.HasPrefix(rel, "cmd/infercrane/") {
				collectMatches(commandPattern, data, commands, 1)
			}
			if strings.HasPrefix(rel, "internal/store/") {
				collectMatches(tablePattern, data, tables, 1)
			}
		}
		if strings.HasPrefix(rel, "internal/store/migrations/") && strings.HasSuffix(rel, ".sql") {
			migrations = append(migrations, rel)
			collectMatches(tablePattern, data, tables, 1)
		}
		if strings.HasPrefix(rel, "docs/adr/") && strings.HasSuffix(rel, ".md") && filepath.Base(rel) != "README.md" && filepath.Base(rel) != "index.md" {
			adrs = append(adrs, rel)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return render(packages, sortedKeys(commands), sortedKeys(endpoints), sortedKeys(envs), sortedKeys(tables), sorted(migrations), sorted(adrs)), nil
}

func skipRepositoryDirectory(rel string) bool {
	switch rel {
	case ".git", ".venv", ".infercrane", "bin", "dist", "build", "node_modules", "docs/node_modules", "docs/.mintlify":
		return true
	default:
		return false
	}
}

func render(packages map[string]*packageInfo, commands, endpoints, envs, tables, migrations, adrs []string) []byte {
	var b strings.Builder
	b.WriteString("{/* Code generated by tools/repo-context; DO NOT EDIT. */}\n\n# Repository map\n\nRegenerate with `make context`. Design authority remains in ADRs and feature documentation.\n\n")
	b.WriteString("## Go packages\n\n| Package path | Source files | Test files | Test functions |\n|---|---:|---:|---|\n")
	paths := make([]string, 0, len(packages))
	for path := range packages {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		info := packages[path]
		sort.Strings(info.Tests)
		tests := "—"
		if len(info.Tests) > 0 {
			tests = "`" + strings.Join(info.Tests, "`, `") + "`"
		}
		fmt.Fprintf(&b, "| `%s` | %d | %d | %s |\n", path, info.GoFiles, info.TestFiles, tests)
	}
	writeList(&b, "CLI commands", commands, true)
	writeList(&b, "HTTP endpoints", endpoints, true)
	writeList(&b, "Configuration variables", envs, true)
	writeList(&b, "PostgreSQL tables", tables, true)
	writeList(&b, "Embedded migrations", migrations, true)
	writeList(&b, "Architecture decisions", adrs, false)
	return []byte(b.String())
}

func writeList(b *strings.Builder, title string, items []string, code bool) {
	fmt.Fprintf(b, "\n## %s\n\n", title)
	if len(items) == 0 {
		b.WriteString("None discovered.\n")
		return
	}
	for _, item := range items {
		if code {
			fmt.Fprintf(b, "- `%s`\n", item)
		} else {
			fmt.Fprintf(b, "- [%s](../%s)\n", filepath.Base(item), strings.TrimPrefix(item, "docs/"))
		}
	}
}
func collectMatches(pattern *regexp.Regexp, data []byte, destination map[string]struct{}, group int) {
	for _, match := range pattern.FindAllSubmatch(data, -1) {
		destination[string(match[group])] = struct{}{}
	}
}
func sortedKeys(values map[string]struct{}) []string {
	out := make([]string, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	return sorted(out)
}
func sorted(values []string) []string { sort.Strings(values); return values }
func relative(root, path string) string {
	rel, _ := filepath.Rel(root, path)
	return filepath.ToSlash(rel)
}
func repositoryRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}
func validateLinks(root string) error {
	return filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel := relative(root, path)
		if entry.IsDir() {
			if skipRepositoryDirectory(rel) {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".md") && !strings.HasSuffix(path, ".mdx") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		for _, match := range linkPattern.FindAllSubmatch(data, -1) {
			target := string(match[1])
			if strings.Contains(target, "://") || strings.HasPrefix(target, "#") || strings.HasPrefix(target, "mailto:") {
				continue
			}
			target = strings.SplitN(target, "#", 2)[0]
			if target == "" {
				continue
			}
			if strings.HasPrefix(target, "/") {
				resolved := filepath.Join(root, "docs", filepath.FromSlash(strings.TrimPrefix(target, "/")))
				if documentationPathExists(resolved) {
					continue
				}
				return fmt.Errorf("broken link in %s: %s", rel, target)
			}
			resolved := filepath.Clean(filepath.Join(filepath.Dir(path), filepath.FromSlash(target)))
			if !documentationPathExists(resolved) {
				return fmt.Errorf("broken link in %s: %s", rel, target)
			}
		}
		return nil
	})
}

func documentationPathExists(path string) bool {
	for _, candidate := range []string{path, path + ".md", path + ".mdx", filepath.Join(path, "index.md"), filepath.Join(path, "index.mdx")} {
		if _, err := os.Stat(candidate); err == nil {
			return true
		}
	}
	return false
}
func fatal(err error) { fmt.Fprintln(os.Stderr, "repo-context:", err); os.Exit(1) }
