package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/infercrane/infercrane/internal/apicontract"
)

func main() {
	check := flag.Bool("check", false, "fail when generated output differs")
	flag.Parse()
	data, err := apicontract.Marshal()
	if err != nil {
		fatal(err)
	}
	outputs := map[string][]byte{
		"api/openapi.json":  data,
		"docs/openapi.json": data,
		"sdk/python/src/infercrane/generated/models.py": []byte(pythonModels),
		"sdk/python/src/infercrane/generated/api.py":    []byte(pythonAPI()),
		"sdk/typescript/src/generated/models.ts":        []byte(typeScriptModels),
		"sdk/typescript/src/generated/api.ts":           []byte(typeScriptAPI()),
	}
	paths := make([]string, 0, len(outputs))
	for path := range outputs {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, slashPath := range paths {
		path, contents := filepath.FromSlash(slashPath), outputs[slashPath]
		if !bytes.HasSuffix(contents, []byte("\n")) {
			contents = append(contents, '\n')
		}
		if *check {
			existing, readErr := os.ReadFile(path)
			if readErr != nil || !bytes.Equal(existing, contents) {
				fatal(fmt.Errorf("%s is stale; run make generate-api", slashPath))
			}
			continue
		}
		if err = os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fatal(err)
		}
		if err = os.WriteFile(path, contents, 0o644); err != nil {
			fatal(err)
		}
	}
}

func fatal(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }

var pathParameterPattern = regexp.MustCompile(`\{([^}]+)\}`)

func snake(value string) string {
	var out []rune
	for i, current := range value {
		if i > 0 && current >= 'A' && current <= 'Z' {
			out = append(out, '_')
		}
		out = append(out, []rune(strings.ToLower(string(current)))...)
	}
	return string(out)
}

func parameters(path string) []string {
	matches := pathParameterPattern.FindAllStringSubmatch(path, -1)
	result := make([]string, 0, len(matches))
	for _, match := range matches {
		result = append(result, match[1])
	}
	return result
}

func pythonAPI() string {
	var out strings.Builder
	out.WriteString("# Code generated by tools/openapi-codegen; DO NOT EDIT.\nfrom __future__ import annotations\n\nfrom typing import Any, Protocol, cast\nfrom urllib.parse import quote\n\nfrom .models import DeploymentList, DeploymentOperationEnvelope, DeploymentView, IntentPlanEnvelope, ObjectList, OperationData, OperationEnvelope\n\n\nclass Transport(Protocol):\n    def request(self, method: str, path: str, *, body: Any | None = None, idempotency_key: str | None = None) -> Any: ...\n\n\nclass ControlAPI:\n    def __init__(self, transport: Transport) -> None:\n        self._transport = transport\n")
	for _, route := range apicontract.Routes {
		out.WriteString("\n    def " + snake(route.OperationID) + "(self")
		for _, parameter := range parameters(route.Path) {
			out.WriteString(", " + parameter + ": str")
		}
		if route.Request != "" {
			out.WriteString(", *, body: dict[str, Any]")
		}
		if route.Idempotent {
			out.WriteString(", idempotency_key: str")
		}
		responseType := pythonResponseType(route.Response)
		out.WriteString(") -> " + responseType + ":\n")
		if len(parameters(route.Path)) > 0 {
			path := route.Path
			for _, parameter := range parameters(route.Path) {
				path = strings.ReplaceAll(path, "{"+parameter+"}", "{quote("+parameter+", safe='')}")
			}
			out.WriteString("        path = f\"" + path + "\"\n")
		} else {
			out.WriteString("        path = \"" + route.Path + "\"\n")
		}
		out.WriteString("        return cast(" + responseType + ", self._transport.request(\"" + route.Method + "\", path")
		if route.Request != "" {
			out.WriteString(", body=body")
		}
		if route.Idempotent {
			out.WriteString(", idempotency_key=idempotency_key")
		}
		out.WriteString("))\n")
	}
	return out.String()
}

func typeScriptAPI() string {
	var out strings.Builder
	out.WriteString("// Code generated by tools/openapi-codegen; DO NOT EDIT.\nimport type { DeploymentList, DeploymentOperationEnvelope, DeploymentView, IntentPlanEnvelope, JsonValue, ObjectList, Operation, OperationEnvelope } from './models.js';\n\nexport interface ApiTransport {\n  request(method: string, path: string, options?: { body?: JsonValue; idempotencyKey?: string }): Promise<unknown>;\n}\n\nexport class ControlApi {\n  constructor(private readonly transport: ApiTransport) {}\n")
	for _, route := range apicontract.Routes {
		out.WriteString("\n  " + route.OperationID + "(")
		args := []string{}
		for _, parameter := range parameters(route.Path) {
			args = append(args, parameter+": string")
		}
		if route.Request != "" {
			args = append(args, "body: JsonValue")
		}
		if route.Idempotent {
			args = append(args, "idempotencyKey: string")
		}
		responseType := typeScriptResponseType(route.Response)
		out.WriteString(strings.Join(args, ", ") + "): Promise<" + responseType + "> {\n")
		path := route.Path
		for _, parameter := range parameters(route.Path) {
			path = strings.ReplaceAll(path, "{"+parameter+"}", "${encodeURIComponent("+parameter+")}")
		}
		if len(parameters(route.Path)) > 0 {
			out.WriteString("    const path = `" + path + "`;\n")
		} else {
			out.WriteString("    const path = '" + path + "';\n")
		}
		options := []string{}
		if route.Request != "" {
			options = append(options, "body")
		}
		if route.Idempotent {
			options = append(options, "idempotencyKey")
		}
		if len(options) > 0 {
			out.WriteString("    return this.transport.request('" + route.Method + "', path, { " + strings.Join(options, ", ") + " }) as Promise<" + responseType + ">;\n")
		} else {
			out.WriteString("    return this.transport.request('" + route.Method + "', path) as Promise<" + responseType + ">;\n")
		}
		out.WriteString("  }\n")
	}
	out.WriteString("}\n")
	return out.String()
}

func pythonResponseType(schema string) string {
	switch schema {
	case "Operation":
		return "OperationData"
	case "OperationEnvelope", "DeploymentOperationEnvelope", "DeploymentList", "DeploymentView", "IntentPlanEnvelope", "ObjectList":
		return schema
	case "Empty":
		return "None"
	default:
		return "dict[str, Any]"
	}
}

func typeScriptResponseType(schema string) string {
	switch schema {
	case "Operation", "OperationEnvelope", "DeploymentOperationEnvelope", "DeploymentList", "DeploymentView", "IntentPlanEnvelope", "ObjectList":
		return schema
	case "Empty":
		return "void"
	default:
		return "Record<string, JsonValue>"
	}
}

const pythonModels = `# Code generated by tools/openapi-codegen; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal, TypedDict

OperationStatus = Literal["pending", "leased", "running", "waiting", "cancelling", "succeeded", "failed", "cancelled"]

@dataclass(frozen=True)
class Operation:
    id: str
    kind: str
    status: OperationStatus
    progress: int
    message: str = ""
    current_step: str = ""
    current_step_status: str = ""
    resource_type: str = ""
    resource_name: str = ""
    error_code: str = ""
    retryable: bool = False
    cancel_requested: bool = False
    attempt: int = 0
    max_attempts: int = 0
    result: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "Operation":
        fields = cls.__dataclass_fields__
        return cls(**{key: item for key, item in value.items() if key in fields})

@dataclass(frozen=True)
class Deployment:
    name: str
    model: str
    runtime: str
    id: str = ""
    observed_state: str = ""
    min_replicas: int = 0
    max_replicas: int = 0
    active_revision_id: str = ""
    candidate_revision_id: str = ""

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "Deployment":
        fields = cls.__dataclass_fields__
        return cls(**{key: item for key, item in value.items() if key in fields})

class OperationDataRequired(TypedDict):
    id: str
    kind: str
    status: OperationStatus
    progress: int

class OperationData(OperationDataRequired, total=False):
    message: str
    current_step: str
    current_step_status: str
    resource_type: str
    resource_name: str
    error_code: str
    retryable: bool
    cancel_requested: bool
    attempt: int
    max_attempts: int
    result: dict[str, Any]

class DeploymentData(TypedDict):
    name: str
    model: str
    runtime: str

class OperationEnvelopeRequired(TypedDict):
    operation: OperationData

class OperationEnvelope(OperationEnvelopeRequired, total=False):
    created: bool

class DeploymentOperationEnvelope(OperationEnvelope, total=False):
    deployment: DeploymentData

class DeploymentList(TypedDict):
    data: list[DeploymentData]

class DeploymentViewRequired(TypedDict):
    deployment: DeploymentData
    lifecycle_status: dict[str, Any]

class DeploymentView(DeploymentViewRequired, total=False):
    active_operation: OperationData
    targets: list[dict[str, Any]]
    replicas: list[dict[str, Any]]
    revisions: list[dict[str, Any]]

class ObjectList(TypedDict):
    data: list[dict[str, Any]]

class IntentPlanOptionRequired(TypedDict):
    value: str
    label: str

class IntentPlanOption(IntentPlanOptionRequired, total=False):
    state: str
    reason: str

class IntentPlanChoiceRequired(TypedDict):
    field: str
    label: str
    editable: bool
    required: bool

class IntentPlanChoice(IntentPlanChoiceRequired, total=False):
    value: str | int
    options: list[IntentPlanOption]

class IntentPlanMissingChoiceRequired(TypedDict):
    field: str
    prompt: str
    reason: str
    remediation: str

class IntentPlanMissingChoice(IntentPlanMissingChoiceRequired, total=False):
    options: list[IntentPlanOption]

class IntentPlanInterpretationRequired(TypedDict):
    action: Literal["deploy", "optimize"]
    objective: Literal["interactive", "latency", "throughput", "cost-efficiency"]

class IntentPlanInterpretation(IntentPlanInterpretationRequired, total=False):
    compute_mode: Literal["elastic", "serverless"]

class IntentPlanModel(TypedDict):
    name: str
    display_name: str
    repository: str
    revision: str
    runtime: str
    tasks: list[str]
    gated: bool
    evidence_class: str
    evidence_summary: str

class IntentPlanConfigurationRequired(TypedDict):
    model: str
    model_revision: str
    runtime: str
    runtime_args: list[str]
    profile: str
    compute_mode: Literal["elastic", "serverless"]
    gpu: str
    gpu_count: int
    min_replicas: int
    max_replicas: int
    routing: str

class IntentPlanConfiguration(IntentPlanConfigurationRequired, total=False):
    runtime_version: str
    provider: str
    provider_adapter: str
    region: str

class IntentPlanPriceEvidenceRequired(TypedDict):
    state: Literal["current", "unavailable"]
    deployment_comparable: bool
    reason: str

class IntentPlanPriceEvidence(IntentPlanPriceEvidenceRequired, total=False):
    currency: str
    hourly_usd_per_replica: float
    cost_scope: str
    price_authority: str
    source: str
    observed_at: str
    valid_until: str

class IntentPlanEvidence(TypedDict):
    configuration: str
    performance: str
    capacity: str
    price: IntentPlanPriceEvidence

class IntentPlanNode(TypedDict):
    id: str
    kind: str
    label: str
    state: str

IntentPlanEdge = TypedDict("IntentPlanEdge", {"from": str, "to": str, "label": str})

class IntentPlanArchitecture(TypedDict):
    nodes: list[IntentPlanNode]
    edges: list[IntentPlanEdge]

class IntentDeploymentDraftRequired(TypedDict):
    name: str
    model: str
    cloud: str
    gpu: str

class IntentDeploymentDraft(IntentDeploymentDraftRequired, total=False):
    endpoint_name: str
    runtime: str
    provider_adapter: str
    compute_mode: Literal["elastic", "serverless"]
    gpu_count: int
    region: str
    runtime_version: str
    model_revision: str
    runtime_args: list[str]
    port: int
    min_replicas: int
    max_replicas: int
    workload: dict[str, Any]
    serving: dict[str, Any]

class IntentPlanRequired(TypedDict):
    schema_version: Literal["infercrane.intent-plan/v1"]
    status: Literal["ready", "needs_input"]
    mutation: Literal["none"]
    interpretation: IntentPlanInterpretation
    choices: list[IntentPlanChoice]
    missing_choices: list[IntentPlanMissingChoice]
    architecture: IntentPlanArchitecture
    evidence: IntentPlanEvidence
    warnings: list[str]

class IntentPlan(IntentPlanRequired, total=False):
    model: IntentPlanModel
    configuration: IntentPlanConfiguration

class IntentPlanEnvelopeRequired(TypedDict):
    plan: IntentPlan
    provider_mutation: bool
    capacity_reserved: bool
    performance_claims: bool
    selection_boundary: str

class IntentPlanEnvelope(IntentPlanEnvelopeRequired, total=False):
    deployment_draft: IntentDeploymentDraft
`

const typeScriptModels = `// Code generated by tools/openapi-codegen; DO NOT EDIT.
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type OperationStatus = 'pending' | 'leased' | 'running' | 'waiting' | 'cancelling' | 'succeeded' | 'failed' | 'cancelled';

export interface Operation {
  id: string;
  kind: string;
  status: OperationStatus;
  progress: number;
  message?: string;
  current_step?: string;
  current_step_status?: string;
  resource_type?: string;
  resource_name?: string;
  error_code?: string;
  retryable?: boolean;
  cancel_requested?: boolean;
  attempt?: number;
  max_attempts?: number;
  result?: Record<string, JsonValue>;
}

export interface Deployment {
  id?: string;
  name: string;
  model: string;
  runtime: string;
  observed_state?: string;
  min_replicas?: number;
  max_replicas?: number;
  active_revision_id?: string;
  candidate_revision_id?: string;
}

export interface OperationEnvelope {
  operation: Operation;
  created?: boolean;
}

export interface DeploymentOperationEnvelope extends OperationEnvelope {
  deployment?: Deployment;
}

export interface DeploymentList {
  data: Deployment[];
}

export interface DeploymentView {
  deployment: Deployment;
  lifecycle_status: Record<string, JsonValue>;
  active_operation?: Operation;
  targets?: Array<Record<string, JsonValue>>;
  replicas?: Array<Record<string, JsonValue>>;
  revisions?: Array<Record<string, JsonValue>>;
}

export interface ObjectList {
  data: Array<Record<string, JsonValue>>;
}

export interface IntentPlanOption {
  value: string;
  label: string;
  state?: string;
  reason?: string;
}

export interface IntentPlanChoice {
  field: string;
  label: string;
  value?: string | number;
  editable: boolean;
  required: boolean;
  options?: IntentPlanOption[];
}

export interface IntentPlanMissingChoice {
  field: string;
  prompt: string;
  reason: string;
  options?: IntentPlanOption[];
  remediation: string;
}

export interface IntentPlanInterpretation {
  action: 'deploy' | 'optimize';
  objective: 'interactive' | 'latency' | 'throughput' | 'cost-efficiency';
  compute_mode?: 'elastic' | 'serverless';
}

export interface IntentPlanModel {
  name: string;
  display_name: string;
  repository: string;
  revision: string;
  runtime: string;
  tasks: string[];
  gated: boolean;
  evidence_class: string;
  evidence_summary: string;
}

export interface IntentPlanConfiguration {
  model: string;
  model_revision: string;
  runtime: string;
  runtime_version?: string;
  runtime_args: string[];
  profile: string;
  compute_mode: 'elastic' | 'serverless';
  provider?: string;
  provider_adapter?: string;
  region?: string;
  gpu: string;
  gpu_count: number;
  min_replicas: number;
  max_replicas: number;
  routing: string;
}

export interface IntentPlanPriceEvidence {
  state: 'current' | 'unavailable';
  currency?: string;
  hourly_usd_per_replica?: number;
  cost_scope?: string;
  price_authority?: string;
  source?: string;
  observed_at?: string;
  valid_until?: string;
  deployment_comparable: boolean;
  reason: string;
}

export interface IntentPlanEvidence {
  configuration: string;
  performance: string;
  capacity: string;
  price: IntentPlanPriceEvidence;
}

export interface IntentPlanNode {
  id: string;
  kind: string;
  label: string;
  state: string;
}

export interface IntentPlanEdge {
  from: string;
  to: string;
  label: string;
}

export interface IntentPlanArchitecture {
  nodes: IntentPlanNode[];
  edges: IntentPlanEdge[];
}

export interface IntentDeploymentDraft {
  name: string;
  endpoint_name?: string;
  model: string;
  runtime?: string;
  cloud: string;
  provider_adapter?: string;
  compute_mode?: 'elastic' | 'serverless';
  gpu: string;
  gpu_count?: number;
  region?: string;
  runtime_version?: string;
  model_revision?: string;
  runtime_args?: string[];
  port?: number;
  min_replicas?: number;
  max_replicas?: number;
  workload?: Record<string, JsonValue>;
  serving?: Record<string, JsonValue>;
}

export interface IntentPlan {
  schema_version: 'infercrane.intent-plan/v1';
  status: 'ready' | 'needs_input';
  mutation: 'none';
  interpretation: IntentPlanInterpretation;
  model?: IntentPlanModel;
  configuration?: IntentPlanConfiguration;
  choices: IntentPlanChoice[];
  missing_choices: IntentPlanMissingChoice[];
  architecture: IntentPlanArchitecture;
  evidence: IntentPlanEvidence;
  warnings: string[];
}

export interface IntentPlanEnvelope {
  plan: IntentPlan;
  deployment_draft?: IntentDeploymentDraft;
  provider_mutation: false;
  capacity_reserved: false;
  performance_claims: false;
  selection_boundary: string;
}
`
