package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/infercrane/infercrane/internal/apicontract"
)

func main() {
	check := flag.Bool("check", false, "fail when generated output differs")
	flag.Parse()
	data, err := apicontract.Marshal()
	if err != nil {
		fatal(err)
	}
	outputs := map[string][]byte{
		"api/openapi.json":  data,
		"docs/openapi.json": data,
		"sdk/python/src/infercrane/generated/models.py": []byte(pythonModels),
		"sdk/python/src/infercrane/generated/api.py":    []byte(pythonAPI()),
		"sdk/typescript/src/generated/models.ts":        []byte(typeScriptModels),
		"sdk/typescript/src/generated/api.ts":           []byte(typeScriptAPI()),
	}
	paths := make([]string, 0, len(outputs))
	for path := range outputs {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, slashPath := range paths {
		path, contents := filepath.FromSlash(slashPath), outputs[slashPath]
		if !bytes.HasSuffix(contents, []byte("\n")) {
			contents = append(contents, '\n')
		}
		if *check {
			existing, readErr := os.ReadFile(path)
			if readErr != nil || !bytes.Equal(existing, contents) {
				fatal(fmt.Errorf("%s is stale; run make generate-api", slashPath))
			}
			continue
		}
		if err = os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fatal(err)
		}
		if err = os.WriteFile(path, contents, 0o644); err != nil {
			fatal(err)
		}
	}
}

func fatal(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }

var pathParameterPattern = regexp.MustCompile(`\{([^}]+)\}`)

func snake(value string) string {
	var out []rune
	for i, current := range value {
		if i > 0 && current >= 'A' && current <= 'Z' {
			out = append(out, '_')
		}
		out = append(out, []rune(strings.ToLower(string(current)))...)
	}
	return string(out)
}

func parameters(path string) []string {
	matches := pathParameterPattern.FindAllStringSubmatch(path, -1)
	result := make([]string, 0, len(matches))
	for _, match := range matches {
		result = append(result, match[1])
	}
	return result
}

func pythonAPI() string {
	var out strings.Builder
	out.WriteString("# Code generated by tools/openapi-codegen; DO NOT EDIT.\nfrom __future__ import annotations\n\nfrom typing import Any, Protocol, cast\nfrom urllib.parse import quote\n\nfrom .models import DeploymentList, DeploymentOperationEnvelope, DeploymentView, ObjectList, OperationData, OperationEnvelope\n\n\nclass Transport(Protocol):\n    def request(self, method: str, path: str, *, body: Any | None = None, idempotency_key: str | None = None) -> Any: ...\n\n\nclass ControlAPI:\n    def __init__(self, transport: Transport) -> None:\n        self._transport = transport\n")
	for _, route := range apicontract.Routes {
		out.WriteString("\n    def " + snake(route.OperationID) + "(self")
		for _, parameter := range parameters(route.Path) {
			out.WriteString(", " + parameter + ": str")
		}
		if route.Request != "" {
			out.WriteString(", *, body: dict[str, Any]")
		}
		if route.Idempotent {
			out.WriteString(", idempotency_key: str")
		}
		responseType := pythonResponseType(route.Response)
		out.WriteString(") -> " + responseType + ":\n")
		if len(parameters(route.Path)) > 0 {
			path := route.Path
			for _, parameter := range parameters(route.Path) {
				path = strings.ReplaceAll(path, "{"+parameter+"}", "{quote("+parameter+", safe='')}")
			}
			out.WriteString("        path = f\"" + path + "\"\n")
		} else {
			out.WriteString("        path = \"" + route.Path + "\"\n")
		}
		out.WriteString("        return cast(" + responseType + ", self._transport.request(\"" + route.Method + "\", path")
		if route.Request != "" {
			out.WriteString(", body=body")
		}
		if route.Idempotent {
			out.WriteString(", idempotency_key=idempotency_key")
		}
		out.WriteString("))\n")
	}
	return out.String()
}

func typeScriptAPI() string {
	var out strings.Builder
	out.WriteString("// Code generated by tools/openapi-codegen; DO NOT EDIT.\nimport type { DeploymentList, DeploymentOperationEnvelope, DeploymentView, JsonValue, ObjectList, Operation, OperationEnvelope } from './models.js';\n\nexport interface ApiTransport {\n  request(method: string, path: string, options?: { body?: JsonValue; idempotencyKey?: string }): Promise<unknown>;\n}\n\nexport class ControlApi {\n  constructor(private readonly transport: ApiTransport) {}\n")
	for _, route := range apicontract.Routes {
		out.WriteString("\n  " + route.OperationID + "(")
		args := []string{}
		for _, parameter := range parameters(route.Path) {
			args = append(args, parameter+": string")
		}
		if route.Request != "" {
			args = append(args, "body: JsonValue")
		}
		if route.Idempotent {
			args = append(args, "idempotencyKey: string")
		}
		responseType := typeScriptResponseType(route.Response)
		out.WriteString(strings.Join(args, ", ") + "): Promise<" + responseType + "> {\n")
		path := route.Path
		for _, parameter := range parameters(route.Path) {
			path = strings.ReplaceAll(path, "{"+parameter+"}", "${encodeURIComponent("+parameter+")}")
		}
		if len(parameters(route.Path)) > 0 {
			out.WriteString("    const path = `" + path + "`;\n")
		} else {
			out.WriteString("    const path = '" + path + "';\n")
		}
		options := []string{}
		if route.Request != "" {
			options = append(options, "body")
		}
		if route.Idempotent {
			options = append(options, "idempotencyKey")
		}
		if len(options) > 0 {
			out.WriteString("    return this.transport.request('" + route.Method + "', path, { " + strings.Join(options, ", ") + " }) as Promise<" + responseType + ">;\n")
		} else {
			out.WriteString("    return this.transport.request('" + route.Method + "', path) as Promise<" + responseType + ">;\n")
		}
		out.WriteString("  }\n")
	}
	out.WriteString("}\n")
	return out.String()
}

func pythonResponseType(schema string) string {
	switch schema {
	case "Operation":
		return "OperationData"
	case "OperationEnvelope", "DeploymentOperationEnvelope", "DeploymentList", "DeploymentView", "ObjectList":
		return schema
	case "Empty":
		return "None"
	default:
		return "dict[str, Any]"
	}
}

func typeScriptResponseType(schema string) string {
	switch schema {
	case "Operation", "OperationEnvelope", "DeploymentOperationEnvelope", "DeploymentList", "DeploymentView", "ObjectList":
		return schema
	case "Empty":
		return "void"
	default:
		return "Record<string, JsonValue>"
	}
}

const pythonModels = `# Code generated by tools/openapi-codegen; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal, TypedDict

OperationStatus = Literal["pending", "leased", "running", "waiting", "cancelling", "succeeded", "failed", "cancelled"]

@dataclass(frozen=True)
class Operation:
    id: str
    kind: str
    status: OperationStatus
    progress: int
    message: str = ""
    resource_type: str = ""
    resource_name: str = ""
    error_code: str = ""
    retryable: bool = False
    cancel_requested: bool = False
    attempt: int = 0
    max_attempts: int = 0
    result: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "Operation":
        fields = cls.__dataclass_fields__
        return cls(**{key: item for key, item in value.items() if key in fields})

@dataclass(frozen=True)
class Deployment:
    name: str
    model: str
    runtime: str
    id: str = ""
    observed_state: str = ""
    min_replicas: int = 0
    max_replicas: int = 0
    active_revision_id: str = ""
    candidate_revision_id: str = ""

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "Deployment":
        fields = cls.__dataclass_fields__
        return cls(**{key: item for key, item in value.items() if key in fields})

class OperationDataRequired(TypedDict):
    id: str
    kind: str
    status: OperationStatus
    progress: int

class OperationData(OperationDataRequired, total=False):
    message: str
    resource_type: str
    resource_name: str
    error_code: str
    retryable: bool
    cancel_requested: bool
    attempt: int
    max_attempts: int
    result: dict[str, Any]

class DeploymentData(TypedDict):
    name: str
    model: str
    runtime: str

class OperationEnvelopeRequired(TypedDict):
    operation: OperationData

class OperationEnvelope(OperationEnvelopeRequired, total=False):
    created: bool

class DeploymentOperationEnvelope(OperationEnvelope, total=False):
    deployment: DeploymentData

class DeploymentList(TypedDict):
    data: list[DeploymentData]

class DeploymentViewRequired(TypedDict):
    deployment: DeploymentData
    lifecycle_status: dict[str, Any]

class DeploymentView(DeploymentViewRequired, total=False):
    active_operation: OperationData
    targets: list[dict[str, Any]]
    replicas: list[dict[str, Any]]
    revisions: list[dict[str, Any]]

class ObjectList(TypedDict):
    data: list[dict[str, Any]]
`

const typeScriptModels = `// Code generated by tools/openapi-codegen; DO NOT EDIT.
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type OperationStatus = 'pending' | 'leased' | 'running' | 'waiting' | 'cancelling' | 'succeeded' | 'failed' | 'cancelled';

export interface Operation {
  id: string;
  kind: string;
  status: OperationStatus;
  progress: number;
  message?: string;
  resource_type?: string;
  resource_name?: string;
  error_code?: string;
  retryable?: boolean;
  cancel_requested?: boolean;
  attempt?: number;
  max_attempts?: number;
  result?: Record<string, JsonValue>;
}

export interface Deployment {
  id?: string;
  name: string;
  model: string;
  runtime: string;
  observed_state?: string;
  min_replicas?: number;
  max_replicas?: number;
  active_revision_id?: string;
  candidate_revision_id?: string;
}

export interface OperationEnvelope {
  operation: Operation;
  created?: boolean;
}

export interface DeploymentOperationEnvelope extends OperationEnvelope {
  deployment?: Deployment;
}

export interface DeploymentList {
  data: Deployment[];
}

export interface DeploymentView {
  deployment: Deployment;
  lifecycle_status: Record<string, JsonValue>;
  active_operation?: Operation;
  targets?: Array<Record<string, JsonValue>>;
  replicas?: Array<Record<string, JsonValue>>;
  revisions?: Array<Record<string, JsonValue>>;
}

export interface ObjectList {
  data: Array<Record<string, JsonValue>>;
}
`
